Latest

diff --git a/.github/workflows/main_Trial2Cure-V2-2.yml b/.github/workflows/main_Trial2Cure-V2-2.yml
--- a/.github/workflows/main_Trial2Cure-V2-2.yml
+++ b/.github/workflows/main_Trial2Cure-V2-2.yml
@@ -14,7 +14,20 @@ jobs:
     runs-on: 'ubuntu-latest'
 
     steps:
+    # Checkout code with Git LFS support
     - uses: actions/checkout@v2
+      with:
+        lfs: true  # Enables Git LFS to fetch actual files instead of pointers
+
+    # Verify that large JSON file is fetched correctly
+    - name: Verify data.json file
+      run: |
+        if [ -f ./data.json ]; then
+          echo "data.json file exists"
+          ls -lh ./data.json  # List file size to ensure it's correct
+        else
+          echo "Error: data.json file not found!" && exit 1
+        fi
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
@@ -26,6 +39,7 @@ jobs:
         username: ${{ secrets.AzureAppService_ContainerUsername_c3747ab976864998a9d8e76a373e111c }}
         password: ${{ secrets.AzureAppService_ContainerPassword_e57f2d6bfd4b4f8c82f4061fe1574d1d }}
 
+    # Build and push Docker container
     - name: Build and push container image to registry
       uses: docker/build-push-action@v3
       with:
@@ -41,6 +55,7 @@ jobs:
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
     steps:
+    # Deploy to Azure Web App
     - name: Deploy to Azure Web App
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v2
